# IMPORTANDO LIBRERIA DE NUMPY #

In [ ]:

import numpy as np

# CREA UNA LISTA DE 10 ELEMENTOS #

In [1]:
lista1 = list(range(1,11))
lista1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# TRANSFORMANDO LA LISTA A UN ARRAY #

In [4]:
arreglo = np.array(lista1)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# CORROBORANDO EL TIPO DE ESTRUCTURA #

In [7]:
type(arreglo)

numpy.ndarray

# CORROBORANDO EL TIPO DE DATOS DEL ARREGLO #

In [6]:
arreglo.dtype

dtype('int32')

# DEFINIENDO EL ARRAY DE INT32 A FLOAT32 #

In [9]:
np.array(arreglo , dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [8]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# TRANSFORMANDO LOS DATOS DE INT32 A FLOAT32 #

In [10]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)