<h2 style ="color:#00ade4;font-family:Arial">DIMENSIONES</h2>


In [3]:
import numpy as np

<h4 style = "color:cyan"> Generando un Array de 12 elementos enteros con Random </h4>

<image src="assets/img/Vectorv1.png" width=30% alt="Descripción de la imagen">

<image></image>

In [35]:
arreglo = np.random.randint(1,10,12)
arreglo

array([3, 6, 2, 5, 4, 5, 9, 2, 9, 4, 6, 7])

<h4 style = "color:cyan"> Obtener la dimensión de un arreglo </h4>

In [39]:
np.shape(arreglo)

(12,)

<h4 style = "color:cyan"> Transformación del vector de 12 elementos a Matriz 4x3 con Reshape </h4>


<image src="assets/img/matrix.png" width=25% alt="Descripción de la imagen">


In [56]:
matriz = arreglo.reshape(3,4)
matriz

array([[3, 6, 2, 5],
       [4, 5, 9, 2],
       [9, 4, 6, 7]])

<h4 style = "color:cyan">Transformación del vector de 12 elementos a Matriz 4x3 con Reshape </h4>

In [57]:
np.shape(matriz)

(3, 4)

<h4 style = "color:cyan"> Otra Transformación del vector de 9 elementos a Matriz 3x4 con Reshape </h4>


In [8]:
matriz = arreglo.reshape(3,4)
matriz

array([[5, 3, 9, 7],
       [2, 9, 2, 1],
       [3, 6, 4, 8]])

<h4 style = "color:cyan"> Creando un Tensor </h4>

<image src="assets/img/tensor.png" width=30% alt="Descripción de la imagen">


In [58]:
t = [[[[1,2,3],[4,5,6],[7,8,9],[1,2,3]]]]
t

[[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3]]]]